// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacy_Nhom1.Models;

#nullable disable

namespace Pharmacy_Nhom1.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    [Migration("20260717113936_UpdateBatchNumberSeedData")]
    partial class UpdateBatchNumberSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryCode = "K_SINH",
                            CategoryName = "Thuốc kháng sinh",
                            Description = "Kháng sinh trị nhiễm khuẩn, bắt buộc có đơn thuốc",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryCode = "D_DAY",
                            CategoryName = "Thuốc dạ dày - Tiêu hóa",
                            Description = "Hỗ trợ và điều trị viêm loét, trào ngược dạ dày",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryCode = "T_MACH",
                            CategoryName = "Thuốc tim mạch - Huyết áp",
                            Description = "Thuốc tim mạch, hạ huyết áp mạn tính",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryCode = "G_DAU",
                            CategoryName = "Thuốc giảm đau - Hạ sốt",
                            Description = "Thuốc giảm đau thông thường và kháng viêm",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryCode = "H_HAP",
                            CategoryName = "Thuốc ho - Hô hấp",
                            Description = "Siro ho, thuốc long đờm, trị hen suyễn",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryCode = "D_LIEU",
                            CategoryName = "Thuốc da liễu - Bôi ngoài",
                            Description = "Kem bôi da, trị nấm, mụn nhọt, dị ứng",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryCode = "TP_CN",
                            CategoryName = "Vitamin & Thực phẩm chức năng",
                            Description = "Sản phẩm bổ sung, nâng cao sức đề kháng",
                            Status = true
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1L,
                            Address = "12 Vườn Lài, Tân Phú, TP.HCM",
                            CreatedDate = new DateTime(2026, 7, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1291),
                            CustomerCode = "KH001",
                            CustomerGroup = "Thường",
                            FullName = "Trần Văn Hùng",
                            IsActive = true,
                            LoyaltyPoints = 15,
                            Phone = "0908123456",
                            TotalSpent = 158000m
                        },
                        new
                        {
                            CustomerId = 2L,
                            Address = "456 CMT8, Quận 3, TP.HCM",
                            CreatedDate = new DateTime(2026, 7, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1312),
                            CustomerCode = "KH002",
                            CustomerGroup = "Thân thiết",
                            FullName = "Lê Thị Thảo",
                            IsActive = true,
                            LoyaltyPoints = 125,
                            Phone = "0917654321",
                            TotalSpent = 1250000m
                        },
                        new
                        {
                            CustomerId = 3L,
                            Address = "78 Điện Biên Phủ, Bình Thạnh",
                            CreatedDate = new DateTime(2026, 7, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1315),
                            CustomerCode = "KH003",
                            CustomerGroup = "Vip",
                            FullName = "Nguyễn Hoàng Minh",
                            IsActive = true,
                            LoyaltyPoints = 460,
                            Phone = "0983112233",
                            TotalSpent = 4600000m
                        },
                        new
                        {
                            CustomerId = 4L,
                            Address = "22 Lý Thường Kiệt, Tân Bình",
                            CreatedDate = new DateTime(2026, 7, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1317),
                            CustomerCode = "KH004",
                            CustomerGroup = "Thường",
                            FullName = "Phạm Minh Tuấn",
                            IsActive = true,
                            LoyaltyPoints = 8,
                            Phone = "0977889900",
                            TotalSpent = 85000m
                        },
                        new
                        {
                            CustomerId = 5L,
                            Address = "105 Nguyễn Trãi, Quận 5",
                            CreatedDate = new DateTime(2026, 7, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1318),
                            CustomerCode = "KH005",
                            CustomerGroup = "Thân thiết",
                            FullName = "Hoàng Ngọc Mai",
                            IsActive = true,
                            LoyaltyPoints = 210,
                            Phone = "0934556677",
                            TotalSpent = 2100000m
                        },
                        new
                        {
                            CustomerId = 6L,
                            Address = "66 Lê Văn Sỹ, Phú Nhuận",
                            CreatedDate = new DateTime(2026, 7, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1320),
                            CustomerCode = "KH006",
                            CustomerGroup = "Thường",
                            FullName = "Vũ Đình Toàn",
                            IsActive = true,
                            LoyaltyPoints = 0,
                            Phone = "0909998877",
                            TotalSpent = 0m
                        },
                        new
                        {
                            CustomerId = 7L,
                            Address = "19 Đường số 4, Gò Vấp",
                            CreatedDate = new DateTime(2026, 7, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1321),
                            CustomerCode = "KH007",
                            CustomerGroup = "Thường",
                            FullName = "Đỗ Thuý Hạnh",
                            IsActive = true,
                            LoyaltyPoints = 12,
                            Phone = "0918223344",
                            TotalSpent = 124000m
                        },
                        new
                        {
                            CustomerId = 8L,
                            Address = "312 Nguyễn Thị Minh Khai, Q1",
                            CreatedDate = new DateTime(2026, 7, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1323),
                            CustomerCode = "KH008",
                            CustomerGroup = "Vip",
                            FullName = "Bùi Quốc Anh",
                            IsActive = true,
                            LoyaltyPoints = 520,
                            Phone = "0965443322",
                            TotalSpent = 5200000m
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Import", b =>
                {
                    b.Property<long>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImportId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImportCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ImportId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Imports");

                    b.HasData(
                        new
                        {
                            ImportId = 1L,
                            CreatedBy = "Dược sĩ Lê Minh Tâm (Chủ tiệm)",
                            ImportCode = "HDN_001",
                            ImportDate = new DateTime(2026, 6, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1452),
                            Status = (byte)1,
                            SupplierId = 1L,
                            TotalAmount = 5100000m
                        },
                        new
                        {
                            ImportId = 2L,
                            CreatedBy = "Dược sĩ Trần Thị Thu",
                            ImportCode = "HDN_002",
                            ImportDate = new DateTime(2026, 7, 2, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1460),
                            Status = (byte)1,
                            SupplierId = 3L,
                            TotalAmount = 3250000m
                        },
                        new
                        {
                            ImportId = 3L,
                            CreatedBy = "Dược sĩ Vũ Hoàng Hải",
                            ImportCode = "HDN_003",
                            ImportDate = new DateTime(2026, 7, 12, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1462),
                            Status = (byte)1,
                            SupplierId = 4L,
                            TotalAmount = 8400000m
                        },
                        new
                        {
                            ImportId = 4L,
                            CreatedBy = "Dược sĩ Lê Minh Tâm (Chủ tiệm)",
                            ImportCode = "HDN_004",
                            ImportDate = new DateTime(2026, 7, 16, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1463),
                            Status = (byte)1,
                            SupplierId = 5L,
                            TotalAmount = 2900000m
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.ImportDetail", b =>
                {
                    b.Property<long>("ImportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImportDetailId"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OriginalQuantity")
                        .HasColumnType("int");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("ImportDetailId");

                    b.HasIndex("ImportId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportDetails");

                    b.HasData(
                        new
                        {
                            ImportDetailId = 1L,
                            BatchNumber = "LOT-2406-01",
                            CurrentQuantity = 450,
                            ExpiryDate = new DateTime(2028, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 1L,
                            ImportPrice = 1500m,
                            OriginalQuantity = 2000,
                            ProductId = 1L
                        },
                        new
                        {
                            ImportDetailId = 2L,
                            BatchNumber = "LOT-2406-02",
                            CurrentQuantity = 15,
                            ExpiryDate = new DateTime(2027, 9, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 1L,
                            ImportPrice = 17500m,
                            OriginalQuantity = 200,
                            ProductId = 4L
                        },
                        new
                        {
                            ImportDetailId = 3L,
                            BatchNumber = "LOT-2406-03",
                            CurrentQuantity = 300,
                            ExpiryDate = new DateTime(2029, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 1L,
                            ImportPrice = 1000m,
                            OriginalQuantity = 1500,
                            ProductId = 8L
                        },
                        new
                        {
                            ImportDetailId = 4L,
                            BatchNumber = "LOT-2406-04",
                            CurrentQuantity = 8,
                            ExpiryDate = new DateTime(2027, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 1L,
                            ImportPrice = 58000m,
                            OriginalQuantity = 50,
                            ProductId = 14L
                        },
                        new
                        {
                            ImportDetailId = 5L,
                            BatchNumber = "LOT-2407-01",
                            CurrentQuantity = 220,
                            ExpiryDate = new DateTime(2028, 1, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 2L,
                            ImportPrice = 720m,
                            OriginalQuantity = 500,
                            ProductId = 11L
                        },
                        new
                        {
                            ImportDetailId = 6L,
                            BatchNumber = "LOT-2407-02",
                            CurrentQuantity = 120,
                            ExpiryDate = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 2L,
                            ImportPrice = 3200m,
                            OriginalQuantity = 500,
                            ProductId = 5L
                        },
                        new
                        {
                            ImportDetailId = 7L,
                            BatchNumber = "LOT-2407-03",
                            CurrentQuantity = 12,
                            ExpiryDate = new DateTime(2027, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 2L,
                            ImportPrice = 64000m,
                            OriginalQuantity = 30,
                            ProductId = 10L
                        },
                        new
                        {
                            ImportDetailId = 8L,
                            BatchNumber = "LOT-2407-04",
                            CurrentQuantity = 380,
                            ExpiryDate = new DateTime(2028, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 3L,
                            ImportPrice = 6800m,
                            OriginalQuantity = 500,
                            ProductId = 6L
                        },
                        new
                        {
                            ImportDetailId = 9L,
                            BatchNumber = "LOT-2407-05",
                            CurrentQuantity = 260,
                            ExpiryDate = new DateTime(2027, 11, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 3L,
                            ImportPrice = 8500m,
                            OriginalQuantity = 300,
                            ProductId = 7L
                        },
                        new
                        {
                            ImportDetailId = 10L,
                            BatchNumber = "LOT-2407-06",
                            CurrentQuantity = 35,
                            ExpiryDate = new DateTime(2027, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 3L,
                            ImportPrice = 68000m,
                            OriginalQuantity = 40,
                            ProductId = 12L
                        },
                        new
                        {
                            ImportDetailId = 11L,
                            BatchNumber = "LOT-2407-07",
                            CurrentQuantity = 150,
                            ExpiryDate = new DateTime(2027, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 4L,
                            ImportPrice = 13500m,
                            OriginalQuantity = 150,
                            ProductId = 2L
                        },
                        new
                        {
                            ImportDetailId = 12L,
                            BatchNumber = "LOT-2407-08",
                            CurrentQuantity = 500,
                            ExpiryDate = new DateTime(2028, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 4L,
                            ImportPrice = 3100m,
                            OriginalQuantity = 500,
                            ProductId = 3L
                        },
                        new
                        {
                            ImportDetailId = 13L,
                            BatchNumber = "LOT-2407-09",
                            CurrentQuantity = 400,
                            ExpiryDate = new DateTime(2029, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 4L,
                            ImportPrice = 2000m,
                            OriginalQuantity = 400,
                            ProductId = 9L
                        },
                        new
                        {
                            ImportDetailId = 14L,
                            BatchNumber = "LOT-2407-10",
                            CurrentQuantity = 10,
                            ExpiryDate = new DateTime(2028, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 4L,
                            ImportPrice = 250000m,
                            OriginalQuantity = 10,
                            ProductId = 13L
                        },
                        new
                        {
                            ImportDetailId = 15L,
                            BatchNumber = "LOT-2407-11",
                            CurrentQuantity = 25,
                            ExpiryDate = new DateTime(2028, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ImportId = 4L,
                            ImportPrice = 65000m,
                            OriginalQuantity = 25,
                            ProductId = 15L
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PrescriptionFileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PrescriptionFileId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1L,
                            CustomerId = 1L,
                            Discount = 0m,
                            NetAmount = 143000m,
                            OrderCode = "HD_001",
                            OrderDate = new DateTime(2026, 7, 7, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1559),
                            PrescriptionFileId = 1L,
                            Status = true,
                            TotalAmount = 143000m,
                            UserId = 2L
                        },
                        new
                        {
                            OrderId = 2L,
                            CustomerId = 2L,
                            Discount = 14000m,
                            NetAmount = 400000m,
                            OrderCode = "HD_002",
                            OrderDate = new DateTime(2026, 7, 12, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1562),
                            PrescriptionFileId = 3L,
                            Status = false,
                            TotalAmount = 414000m,
                            UserId = 2L
                        },
                        new
                        {
                            OrderId = 3L,
                            CustomerId = 3L,
                            Discount = 0m,
                            NetAmount = 250000m,
                            OrderCode = "HD_003",
                            OrderDate = new DateTime(2026, 7, 15, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1565),
                            PrescriptionFileId = 4L,
                            Status = false,
                            TotalAmount = 250000m,
                            UserId = 3L
                        },
                        new
                        {
                            OrderId = 4L,
                            Discount = 0m,
                            NetAmount = 222000m,
                            OrderCode = "HD_004",
                            OrderDate = new DateTime(2026, 7, 16, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1567),
                            Status = true,
                            TotalAmount = 222000m,
                            UserId = 1L
                        },
                        new
                        {
                            OrderId = 5L,
                            CustomerId = 7L,
                            Discount = 4000m,
                            NetAmount = 120000m,
                            OrderCode = "HD_005",
                            OrderDate = new DateTime(2026, 7, 17, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1569),
                            Status = true,
                            TotalAmount = 124000m,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.OrderDetail", b =>
                {
                    b.Property<long>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderDetailId"));

                    b.Property<int>("ConversionRate")
                        .HasColumnType("int");

                    b.Property<long>("ImportDetailId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SoldUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("ImportDetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1L,
                            ConversionRate = 1,
                            ImportDetailId = 2L,
                            OrderId = 1L,
                            Price = 24000m,
                            Quantity = 2,
                            SoldUnit = "Viên"
                        },
                        new
                        {
                            OrderDetailId = 2L,
                            ConversionRate = 1,
                            ImportDetailId = 10L,
                            OrderId = 1L,
                            Price = 90000m,
                            Quantity = 1,
                            SoldUnit = "Tuýp"
                        },
                        new
                        {
                            OrderDetailId = 3L,
                            ConversionRate = 1,
                            ImportDetailId = 6L,
                            OrderId = 1L,
                            Price = 5000m,
                            Quantity = 1,
                            SoldUnit = "Gói"
                        },
                        new
                        {
                            OrderDetailId = 4L,
                            ConversionRate = 1,
                            ImportDetailId = 8L,
                            OrderId = 2L,
                            Price = 9200m,
                            Quantity = 30,
                            SoldUnit = "Viên"
                        },
                        new
                        {
                            OrderDetailId = 5L,
                            ConversionRate = 1,
                            ImportDetailId = 9L,
                            OrderId = 2L,
                            Price = 11500m,
                            Quantity = 12,
                            SoldUnit = "Viên"
                        },
                        new
                        {
                            OrderDetailId = 6L,
                            ConversionRate = 14,
                            ImportDetailId = 11L,
                            OrderId = 3L,
                            Price = 160000m,
                            Quantity = 1,
                            SoldUnit = "Hộp"
                        },
                        new
                        {
                            OrderDetailId = 7L,
                            ConversionRate = 1,
                            ImportDetailId = 1L,
                            OrderId = 3L,
                            Price = 2500m,
                            Quantity = 36,
                            SoldUnit = "Viên"
                        },
                        new
                        {
                            OrderDetailId = 8L,
                            ConversionRate = 1,
                            ImportDetailId = 7L,
                            OrderId = 4L,
                            Price = 82000m,
                            Quantity = 1,
                            SoldUnit = "Chai"
                        },
                        new
                        {
                            OrderDetailId = 9L,
                            ConversionRate = 1,
                            ImportDetailId = 4L,
                            OrderId = 4L,
                            Price = 78000m,
                            Quantity = 1,
                            SoldUnit = "Viên"
                        },
                        new
                        {
                            OrderDetailId = 10L,
                            ConversionRate = 1,
                            ImportDetailId = 15L,
                            OrderId = 4L,
                            Price = 62000m,
                            Quantity = 1,
                            SoldUnit = "Viên"
                        },
                        new
                        {
                            OrderDetailId = 11L,
                            ConversionRate = 20,
                            ImportDetailId = 13L,
                            OrderId = 5L,
                            Price = 58000m,
                            Quantity = 1,
                            SoldUnit = "Hộp"
                        },
                        new
                        {
                            OrderDetailId = 12L,
                            ConversionRate = 1,
                            ImportDetailId = 6L,
                            OrderId = 5L,
                            Price = 4800m,
                            Quantity = 10,
                            SoldUnit = "Gói"
                        },
                        new
                        {
                            OrderDetailId = 13L,
                            ConversionRate = 10,
                            ImportDetailId = 3L,
                            OrderId = 5L,
                            Price = 18000m,
                            Quantity = 1,
                            SoldUnit = "Vỉ"
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.PrescriptionFile", b =>
                {
                    b.Property<long>("PrescriptionFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PrescriptionFileId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PrescriptionFileId");

                    b.ToTable("PrescriptionFiles");

                    b.HasData(
                        new
                        {
                            PrescriptionFileId = 1L,
                            FileName = "TOA_LOET_DADAY_HUNG.png",
                            FilePath = "toa_daday.png",
                            Note = "Toa thuốc dạ dày - BV Đại học Y Dược",
                            Status = true,
                            UploadDate = new DateTime(2026, 7, 7, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1535)
                        },
                        new
                        {
                            PrescriptionFileId = 2L,
                            FileName = "TOA_VIEMDA_HUNG.png",
                            FilePath = "toa_dalieu.png",
                            Note = "Toa bôi da liễu - Bệnh viện Da Liễu",
                            Status = true,
                            UploadDate = new DateTime(2026, 7, 7, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1537)
                        },
                        new
                        {
                            PrescriptionFileId = 3L,
                            FileName = "TOA_HUYETAP_THAO.png",
                            FilePath = "toa_huyetap.png",
                            Note = "Đơn thuốc huyết áp vô căn mãn tính",
                            Status = true,
                            UploadDate = new DateTime(2026, 6, 22, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1539)
                        },
                        new
                        {
                            PrescriptionFileId = 4L,
                            FileName = "TOA_K_SINH_MINH.png",
                            FilePath = "toa_khangsinh.png",
                            Note = "Toa kháng sinh trị viêm tai giữa",
                            Status = true,
                            UploadDate = new DateTime(2026, 7, 15, 18, 39, 36, 423, DateTimeKind.Local).AddTicks(1540)
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageFile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("NormalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PrescriptionRequired")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            CategoryId = 1,
                            Description = "Kháng sinh phổ rộng nhóm Penicillin, chỉ định điều trị các nhiễm khuẩn đường hô hấp trên và dưới, viêm tai giữa, nhiễm khuẩn da và đường tiết niệu.",
                            PrescriptionRequired = true,
                            Price = 2500m,
                            ProductCode = "AMX500",
                            ProductName = "Amoxicillin 500mg",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 2L,
                            CategoryId = 1,
                            Description = "Kháng sinh kết hợp Amoxicillin và Acid Clavulanic, vượt qua đề kháng của vi khuẩn, trị nhiễm khuẩn nặng tai mũi họng và viêm phế quản.",
                            PrescriptionRequired = true,
                            Price = 16000m,
                            ProductCode = "AUG625",
                            ProductName = "Augmentin 625mg",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 3L,
                            CategoryId = 1,
                            Description = "Kháng sinh Cephalosporin thế hệ 3, điều trị hiệu quả các nhiễm khuẩn đường tiết niệu, viêm phổi, viêm phế quản cấp và mạn tính.",
                            PrescriptionRequired = true,
                            Price = 4500m,
                            ProductCode = "CEF200",
                            ProductName = "Cefixim 200mg",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 4L,
                            CategoryId = 2,
                            Description = "Thuốc ức chế bơm proton (Esomeprazole), chỉ định điều trị trào ngược dạ dày thực quản (GERD), chữa lành và phòng ngừa viêm loét thực quản.",
                            PrescriptionRequired = true,
                            Price = 24000m,
                            ProductCode = "NEX40",
                            ProductName = "Nexium Mups 40mg",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 5L,
                            CategoryId = 2,
                            Description = "Thuốc kháng acid dạng hỗn dịch hỗ trợ làm dịu nhanh cơn đau dạ dày, giảm ợ chua, ợ nóng do thừa acid dịch vị.",
                            PrescriptionRequired = false,
                            Price = 4800m,
                            ProductCode = "PHOS",
                            ProductName = "Phosphalugel",
                            Status = true,
                            Unit = "Gói"
                        },
                        new
                        {
                            ProductId = 6L,
                            CategoryId = 3,
                            Description = "Thuốc chẹn kênh Canxi (Amlodipine), chỉ định trong kiểm soát huyết áp cao mạn tính và điều trị dự phòng cơn đau thắt ngực.",
                            PrescriptionRequired = true,
                            Price = 9200m,
                            ProductCode = "AMLO5",
                            ProductName = "Amlor 5mg",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 7L,
                            CategoryId = 3,
                            Description = "Thuốc phối hợp Amlodipine và Perindopril, kiểm soát huyết áp kép hiệu quả cho bệnh nhân tăng huyết áp vô căn.",
                            PrescriptionRequired = true,
                            Price = 11500m,
                            ProductCode = "COVE",
                            ProductName = "Coveram 5mg/5mg",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 8L,
                            CategoryId = 4,
                            Description = "Thuốc giảm đau, hạ sốt chứa Paracetamol kết hợp Caffeine giúp tăng cường hiệu quả giảm đau đầu, đau cơ, sốt.",
                            PrescriptionRequired = false,
                            Price = 1500m,
                            ProductCode = "PANA_EX",
                            ProductName = "Panadol Extra",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 9L,
                            CategoryId = 4,
                            Description = "Viên sủi Paracetamol 500mg hòa tan nhanh, giảm đau và hạ sốt nhanh chóng, tiện lợi cho người khó nuốt viên nén.",
                            PrescriptionRequired = false,
                            Price = 2900m,
                            ProductCode = "EFF500",
                            ProductName = "Efferalgan Sủi 500mg",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 10L,
                            CategoryId = 5,
                            Description = "Siro thảo dược chiết xuất từ lá thường xuân, có tác dụng long đờm, chống co thắt phế quản, làm dịu cơn ho hiệu quả.",
                            PrescriptionRequired = false,
                            Price = 82000m,
                            ProductCode = "PROS",
                            ProductName = "Siro Ho Prospan 100ml",
                            Status = true,
                            Unit = "Chai"
                        },
                        new
                        {
                            ProductId = 11L,
                            CategoryId = 5,
                            Description = "Viên nang mềm kết hợp các tinh dầu thảo dược thiên nhiên (Eucalyptol, Menthol, Gừng, Tần), giúp ấm đường hô hấp, giảm ho khan.",
                            PrescriptionRequired = false,
                            Price = 1000m,
                            ProductCode = "EXPEC",
                            ProductName = "Eugica Đỏ",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 12L,
                            CategoryId = 6,
                            Description = "Kem bôi da chứa Clobetasol Propionate (Corticoid mạnh), điều trị các bệnh viêm da cơ địa dai dẳng, chàm (Eczema), vẩy nến.",
                            PrescriptionRequired = true,
                            Price = 90000m,
                            ProductCode = "DERMA",
                            ProductName = "Dermovate Cream 15g",
                            Status = true,
                            Unit = "Tuýp"
                        },
                        new
                        {
                            ProductId = 13L,
                            CategoryId = 6,
                            Description = "Gel bôi chứa Azelaic Acid 15%, chuyên trị mụn trứng cá, giảm sưng viêm đỏ, bạt sừng và ngăn ngừa sẹo thâm sau mụn.",
                            PrescriptionRequired = false,
                            Price = 320000m,
                            ProductCode = "SKIN",
                            ProductName = "Skinoren Gel 30g",
                            Status = true,
                            Unit = "Tuýp"
                        },
                        new
                        {
                            ProductId = 14L,
                            CategoryId = 7,
                            Description = "Viên uống bổ sung Vitamin C và các Vitamin nhóm B (B1, B2, B6, B12), tăng sức đề kháng và phục hồi sức khỏe sau ốm.",
                            PrescriptionRequired = false,
                            Price = 1500m,
                            ProductCode = "ENVC",
                            ProductName = "Vitamin C Enervon",
                            Status = true,
                            Unit = "Viên"
                        },
                        new
                        {
                            ProductId = 15L,
                            CategoryId = 7,
                            Description = "Viên sủi chứa hàm lượng cao Vitamin C, B và các khoáng chất (Canxi, Magie, Kẽm), giúp khôi phục năng lượng cho cơ thể.",
                            PrescriptionRequired = false,
                            Price = 8500m,
                            ProductCode = "BERO",
                            ProductName = "Berocca Viên Sủi Bổ Sung",
                            Status = true,
                            Unit = "Viên"
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.ProductUnit", b =>
                {
                    b.Property<long>("ProductUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductUnitId"));

                    b.Property<int>("ConversionRate")
                        .HasColumnType("int");

                    b.Property<decimal?>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductUnitId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductUnits");

                    b.HasData(
                        new
                        {
                            ProductUnitId = 101L,
                            ConversionRate = 10,
                            ImportPrice = 20000m,
                            Price = 26000m,
                            ProductId = 1L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 102L,
                            ConversionRate = 100,
                            ImportPrice = 180000m,
                            Price = 250000m,
                            ProductId = 1L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 103L,
                            ConversionRate = 14,
                            ImportPrice = 190000m,
                            Price = 230000m,
                            ProductId = 2L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 104L,
                            ConversionRate = 28,
                            ImportPrice = 370000m,
                            Price = 450000m,
                            ProductId = 2L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 105L,
                            ConversionRate = 10,
                            ImportPrice = 35000m,
                            Price = 47000m,
                            ProductId = 3L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 106L,
                            ConversionRate = 30,
                            ImportPrice = 100000m,
                            Price = 135000m,
                            ProductId = 3L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 107L,
                            ConversionRate = 14,
                            ImportPrice = 280000m,
                            Price = 340000m,
                            ProductId = 4L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 108L,
                            ConversionRate = 28,
                            ImportPrice = 550000m,
                            Price = 670000m,
                            ProductId = 4L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 109L,
                            ConversionRate = 26,
                            ImportPrice = 100000m,
                            Price = 125000m,
                            ProductId = 5L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 110L,
                            ConversionRate = 10,
                            ImportPrice = 75000m,
                            Price = 95000m,
                            ProductId = 6L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 111L,
                            ConversionRate = 30,
                            ImportPrice = 220000m,
                            Price = 275000m,
                            ProductId = 6L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 112L,
                            ConversionRate = 30,
                            ImportPrice = 280000m,
                            Price = 350000m,
                            ProductId = 7L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 113L,
                            ConversionRate = 30,
                            ImportPrice = 280000m,
                            Price = 350000m,
                            ProductId = 7L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 114L,
                            ConversionRate = 10,
                            ImportPrice = 12000m,
                            Price = 16000m,
                            ProductId = 8L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 115L,
                            ConversionRate = 100,
                            ImportPrice = 110000m,
                            Price = 150000m,
                            ProductId = 8L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 116L,
                            ConversionRate = 4,
                            ImportPrice = 9000m,
                            Price = 12000m,
                            ProductId = 9L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 117L,
                            ConversionRate = 16,
                            ImportPrice = 35000m,
                            Price = 45000m,
                            ProductId = 9L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 118L,
                            ConversionRate = 50,
                            ImportPrice = 3500000m,
                            Price = 4000000m,
                            ProductId = 10L,
                            UnitName = "Thùng"
                        },
                        new
                        {
                            ProductUnitId = 119L,
                            ConversionRate = 10,
                            ImportPrice = 8000m,
                            Price = 11000m,
                            ProductId = 11L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 120L,
                            ConversionRate = 100,
                            ImportPrice = 75000m,
                            Price = 105000m,
                            ProductId = 11L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 121L,
                            ConversionRate = 1,
                            ImportPrice = 80000m,
                            Price = 95000m,
                            ProductId = 12L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 122L,
                            ConversionRate = 1,
                            ImportPrice = 280000m,
                            Price = 330000m,
                            ProductId = 13L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 123L,
                            ConversionRate = 10,
                            ImportPrice = 12000m,
                            Price = 16000m,
                            ProductId = 14L,
                            UnitName = "Vỉ"
                        },
                        new
                        {
                            ProductUnitId = 124L,
                            ConversionRate = 100,
                            ImportPrice = 115000m,
                            Price = 155000m,
                            ProductId = 14L,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            ProductUnitId = 125L,
                            ConversionRate = 10,
                            ImportPrice = 70000m,
                            Price = 86000m,
                            ProductId = 15L,
                            UnitName = "Tuýp"
                        },
                        new
                        {
                            ProductUnitId = 126L,
                            ConversionRate = 20,
                            ImportPrice = 135000m,
                            Price = 170000m,
                            ProductId = 15L,
                            UnitName = "Hộp"
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Supplier", b =>
                {
                    b.Property<long>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1L,
                            Address = "288 Nguyễn Văn Cừ, Cần Thơ",
                            Phone = "02923891433",
                            Status = true,
                            SupplierName = "Công ty Cổ phần Dược Hậu Giang (DHG)",
                            TaxCode = "1800156891"
                        },
                        new
                        {
                            SupplierId = 2L,
                            Address = "1017 Hồng Bàng, Quận 6, TP.HCM",
                            Phone = "02837517111",
                            Status = true,
                            SupplierName = "Công ty Cổ phần Dược phẩm OPC",
                            TaxCode = "0302512345"
                        },
                        new
                        {
                            SupplierId = 3L,
                            Address = "75 Yên Ninh, Ba Đình, Hà Nội",
                            Phone = "18006612",
                            Status = true,
                            SupplierName = "Công ty Cổ phần Traphaco",
                            TaxCode = "0100108656"
                        },
                        new
                        {
                            SupplierId = 4L,
                            Address = "Khu công nghệ cao, Quận 9, TP.HCM",
                            Phone = "02838298526",
                            Status = true,
                            SupplierName = "Dược phẩm Sanofi Việt Nam",
                            TaxCode = "0300624512"
                        },
                        new
                        {
                            SupplierId = 5L,
                            Address = "Lầu 11, Saigon Trade Center, Quận 1, TP.HCM",
                            Phone = "02839102626",
                            Status = true,
                            SupplierName = "Nhà thuốc phân phối sỉ Zuellig Pharma",
                            TaxCode = "0301460351"
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            FullName = "Dược sĩ Lê Minh Tâm (Chủ tiệm)",
                            IsActive = true,
                            PasswordHash = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2L,
                            FullName = "Dược sĩ Trần Thị Thu",
                            IsActive = true,
                            PasswordHash = "thu123",
                            RoleId = 2,
                            Username = "ds_thu"
                        },
                        new
                        {
                            UserId = 3L,
                            FullName = "Dược sĩ Vũ Hoàng Hải",
                            IsActive = true,
                            PasswordHash = "hai123",
                            RoleId = 2,
                            Username = "ds_hai"
                        });
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Import", b =>
                {
                    b.HasOne("Pharmacy_Nhom1.Models.Supplier", "Supplier")
                        .WithMany("Imports")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.ImportDetail", b =>
                {
                    b.HasOne("Pharmacy_Nhom1.Models.Import", "Import")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharmacy_Nhom1.Models.Product", "Product")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Import");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Order", b =>
                {
                    b.HasOne("Pharmacy_Nhom1.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pharmacy_Nhom1.Models.PrescriptionFile", "PrescriptionFile")
                        .WithMany()
                        .HasForeignKey("PrescriptionFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pharmacy_Nhom1.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PrescriptionFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.OrderDetail", b =>
                {
                    b.HasOne("Pharmacy_Nhom1.Models.ImportDetail", "ImportDetail")
                        .WithMany()
                        .HasForeignKey("ImportDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy_Nhom1.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportDetail");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Product", b =>
                {
                    b.HasOne("Pharmacy_Nhom1.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.ProductUnit", b =>
                {
                    b.HasOne("Pharmacy_Nhom1.Models.Product", "Product")
                        .WithMany("ProductUnits")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.User", b =>
                {
                    b.HasOne("Pharmacy_Nhom1.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Import", b =>
                {
                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Product", b =>
                {
                    b.Navigation("ImportDetails");

                    b.Navigation("ProductUnits");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.Supplier", b =>
                {
                    b.Navigation("Imports");
                });

            modelBuilder.Entity("Pharmacy_Nhom1.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
